### PR TITLE
Update to 1.17.1

### PR DESCRIPTION
**Pull request by msfjarvis**
Merges changes from the 1.16 branch and bumps to 1.17.1

### CODE REVIEW

**Comment by OsoaGitHub** [comment]
can you give a build please?

**Comment by ReflectorXD** [comment]
> can you give a build please?

I would also like a build for 1.17

**Comment by msfjarvis** [comment]
I'm not going to be releasing unofficial binaries of someone else's project on their own page, sorry. You'll have to build it yourself.

**Comment by ReflectorXD** [comment]
> I'm not going to be releasing unofficial binaries of someone else's project on their own page, sorry. You'll have to build it yourself.

Understandable

**Comment by basedAF** [comment]
Why is getArmorIdentifier commented out in chimearmor.class? @msfjarvis

**Comment by emilyploszaj** [comment]
Because it was commented out in my quick and dirty chime port to a random snapshot to play with it, it also uses a much dirtier mixin that's going to conflict with things, so I'm pretty sure all the work in the 1.17 actually has to be scrapped and I have to rewrite the port

**Comment by basedAF** [comment]
Sad :( wishing you luck!

**Comment by magicus** [comment]
I've been running with this branch on 1.17.1 for some time, with no issues. I have also created two 1.17 resource packs for Chime, but I'm hesitant to post them publicly, since there is no official 1.17 version of Chime for users to download.

What is blocking just accepting this PR and publishing at least a "beta" stamped version of Chime for 1.17?

**Comment by emilyploszaj** [comment]
you could call it perfectionism if you'd like, but I'm not willing to put out a half-finished mod that has notable compatibility issues and is less complete then the last iteration, my rewrite has had serious progress by now though, so one good day of work can have it out

**Comment by magicus** [comment]
Great! I understand. :) I really like Chime, it fits very naturally into the Vanilla model, and it fills the last gap left from Optifine.

Let me know if there's anything I can do to help, with coding, researching, debugging and/or testing to get 1.17 support perfected!

**Comment by msfjarvis** [comment]
This PR has no business being merged so I'm going to go ahead and close it, I'll keep the branch around on my fork until an official release happens.

**Pull request closed without merging**
