### PR TITLE
1.20 Update.

### PR DESCRIPTION
**Pull request by theendercore**
A 1.20 port. Has been tested in 1.20 - 1.20.2. (All predicates)
Also fixes entity/x running entity.getZ() instead of entity.getX()

### CODE REVIEW

**Review by emilyploszaj — CHANGES_REQUESTED** [review]
Your IDE reformatted the files to use 4 spaces instead of tabs, you'll have to fix that so I can actually read the diff.

**Comment by theendercore** [comment]
Okay that should fix it now. My apologies that I didn't realize.

**Review by emilyploszaj — CHANGES_REQUESTED** [review]
Now that I can see this, why did you run an autoformatter on all of the existing code? I hate to say this again but I still can't tell what's changed since you've changed most of the code.

**Comment by theendercore** [comment]
Okay now it should Actually be good. And once again apologies, I just forgot that I'm working in someone else codebase. And since I don't usually do this, just kind of got carried away.

**Comment by emilyploszaj** [comment]
Sorry for the runaround, this looks great! Thank you for contributing, I'll make a release immediately.

**Comment by bangetto** [comment]
Thank you!

**Pull request merged**
